language: python

python:
- "3.6.7"

install:
  - pip install -r requirements.txt
  - pip install pytest
  
script:
  - pytest

branches:
  only:
    - develop

after_success:
   - coveralls
   - codeclimate-test-reporter
