language: python

python:
- "3.6.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
  
script:
  - pytest --cov=./app

branches:
  only:
    - develop

after_success:
   - coveralls
   - codeclimate-test-reporter